<?php

include "products.class.php";

class Book extends Product
{
    public $weight;

    /**
     * @return mixed
     */
    public function getWeight()
    {
        return $this->weight;
    }

    /**
     * @param mixed $weight
     */
    public function setWeight($weight): void
    {
        $this->weight = $weight;
    }

    public function addProduct()
    {
        parent::addProduct(); // TODO: Change the autogenerated stub
    }
}